name: tipsypal
description: "A TipsyPal application."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.5.0
  flutter_markdown: ^0.7.7+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Ändra Android package name (valfritt)
  change_app_package_name: ^1.5.0

  # App-ikoner
  flutter_launcher_icons: ^0.13.1

  # Splash
  flutter_native_splash: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png

# --- Ikon konfiguration ---
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

# --- Splash konfiguration ---
flutter_native_splash:
  # Ljust läge
  color: "#0B0F17"
  image: assets/icon.png

  # Mörkt läge
  color_dark: "#0B0F17"
  image_dark: assets/icon.png

  # Android 12 kräver eget block
  android_12:
    color: "#0B0F17"
    image: assets/icon.png
    color_dark: "#0B0F17"
    image_dark: assets/icon.png

  branding: assets/branding.png
  branding_dark: assets/branding.png
  
  # Plattformar
  android: true
  ios: true   # sätt till true när du bygger iOS
  web: true